### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by YUNAGATAJJ** [YUNAGATAJJ/orceanize#31]

**Comment by YUNAGATAJJ** [comment]
- [ ] MVPリリース

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます。
以下コメントになります。

---

`<高度機能>画像加工・合成機能`：こちらの機能はどのような操作を行えば確認ができるかを詳しくコメント欄に説明をお願いします。

**Comment by YUNAGATAJJ** [comment]
レビューありがとうございます。
以下に記載いたします。

- <高度機能>画像加工・合成機能
cloudinaryを用いて「投稿された画像に、ロゴが添付される」機能を実装しています。
確認方法としては
- headerのSign-Upを押下、会員登録
[![Image from Gyazo](https://i.gyazo.com/a1e3e13081e341c91906a75e7ebe16f0.png)](https://gyazo.com/a1e3e13081e341c91906a75e7ebe16f0)

- ＋　ボタンを押下し、画像を選択、投稿
[![Image from Gyazo](https://i.gyazo.com/ec4ec9e1b9d0c4ee86f469eaafd3abd1.png)](https://gyazo.com/ec4ec9e1b9d0c4ee86f469eaafd3abd1)

- 投稿された画像の右下あたりに、ロゴが添付されている　のが正の動きになります。
[![Image from Gyazo](https://i.gyazo.com/a3e295c8cca5866d34d41ae7a9cf9db0.jpg)](https://gyazo.com/a3e295c8cca5866d34d41ae7a9cf9db0)

**Comment by YUNAGATAJJ** [comment]
レビューありがとうございます。
承知しました。
