### ISSUE TITLE
Issueベース開発レビュー依頼

### ISSUE THREAD

**Issue by YUNAGATAJJ** [YUNAGATAJJ/orceanize#32]

**Comment by YUNAGATAJJ** [comment]
### 概要
サービス名はOCEANIZE。 
OCEAN(海) と ORGANIZE(構成、整える)を合わせて、海を綺麗な状態にみんなで協力して整えていこうという意味を込めて名付けました。 
海ごみを使用して作成したキャンバスアートを、シェアできるCGM型のサービス。


###実装予定機能

MVPリリース
- [x] 海ごみアート投稿のCRUD機能
- [x] タグ機能
- [x] ゴミの処理方法についての外部ページへのリンク若くは自作のLP(参考文献付き)
- [x] ビーチクリーン活動の外部リンク
- [x] 画像アップロード機能
- [x] <高度機能>画像加工・合成機能
- [x] ログイン・ログアウト機能
- [ ] 
本リリース
- [x] 検索機能
- [x] コメント機能
- [x] PWAによるモバイルアプリ化

###必要なページ

- [x] TOPページ
- [x] Oceanizeについて
- [x] 利用規約
- [x] プライバシーポリシー
- [x] お問合せ
- [x] 外部リンク
- [x] SignUp画面
- [x] SignIn画面
- [x] Home画面
- [x] Create画面
- [x] Show画面
- [x] Edit画面

**Comment by Tsuchiya2** [comment]
...上記講師のコメントと同じになってしまいますが...

看板とストーリポイントが確認できません。対応をお願いいたします。

![スクリーンショット 2023-12-12 9 57 08](https://github.com/YUNAGATAJJ/orceanize/assets/61481161/e45e40f8-c8fe-4100-b2d4-c1060ce770b0)

**Comment by YUNAGATAJJ** [comment]
レビューありがとうございます。
ご不便おかけし申し訳ございません。

以下のように権限をpublicにしましたが、これだといかがでしょうか？

[![Image from Gyazo](https://i.gyazo.com/7d995dafa7f963f507f6e706f136bd23.png)](https://gyazo.com/7d995dafa7f963f507f6e706f136bd23)

[![Image from Gyazo](https://i.gyazo.com/4a4786636e4bfd524f7849d6b15ffd45.png)](https://gyazo.com/4a4786636e4bfd524f7849d6b15ffd45)

**Comment by YUNAGATAJJ** [comment]
大変失礼いたしました。
修正し、再度レビュー投げさせていただきました。

**Comment by beppumasaki** [comment]
対応ありがとうございます！
いいと思います！LGTMです！
